### ISSUE TITLE
Can this be used as a drop-in replacement for libolm?

### ISSUE THREAD

**Issue by anderspitman** [matrix-org/vodozemac#118]
I'm trying to find a way to send a simple e2ee Matrix message from a golang program. mautrix has the functionality, but it dynamically links against libolm. My application currently runs on alpine linux containers and trying to get all the libstdc++ stuff working could be quite the rabbit hole. Ideally I'd like to find a way to statically link a olm/megolm implementation into my app, like I can with sqlite[0]. Building vodozemac as a C library[1] and statically linking it could potentially accomplish this. Is this currently possible, or is there another better way to solve my problem? I can shell out to a bot if necessary but again it would be nice if the bot can be statically linked.

[0]: https://www.arp242.net/static-go.html

[1]: https://docs.rust-embedded.org/book/interoperability/rust-with-c.html

**Comment by poljar** [comment]
Well depends on what you mean by drop-in. This library supports everything libolm supports and you can migrate your data from a libolm based setup.

The API on the other hand, while being similar, is not the same as the one libolm provides. You could make it a bit more similar in your bindings though.

As for the bindings, I would suggest to check out [uniffi](https://github.com/mozilla/uniffi-rs/) and the Go language support for uniffi: https://github.com/NordSecurity/uniffi-bindgen-go.

Sorry for the late reply, I was busy and then away for a bit.

**Comment by poljar** [comment]
Right, this should be answered now.
