### ISSUE TITLE
How to decrypt messages encrypted by self using `olm`

### ISSUE THREAD

**Issue by avp1598** [matrix-org/vodozemac#119]
Hi,
So I am currently encrypting the messages and storing it on a server. Once the user is back, I fetch the encrypted messages and show it. I can decrypt the incoming messages but how do I decrypt the sent messages?

I basically want to decrypt the messages which I encrypted from the same account. Is that possible?

**Comment by avp1598** [comment]
@poljar could you help me here please?

**Comment by poljar** [comment]
This is not supported. It's a conscious choice to drop individual message keys once they have been used, this includes both the encryption path as well as the decryption path.

We drop the individual message key:
1. Once a message is decrypted, making it impossible to decrypt the same message again.
2. Once a message is encrypted, making it impossible to either encrypt another message with the same key or decrypt a message with a key that was used for encryption.
