### ISSUE TITLE
Exposing the library to BEAM as a NIF.

### ISSUE THREAD

**Issue by shymega** [matrix-org/vodozemac#172]
Hi there.

I'm trying to get E2EE working on an IRC <-> Matrix bridge I [forked](https://github.com/shymega/matrix2051-ng). There is a Matrix SDK for Elixir already, but I was thinking of making a PR to bring Vodozemac support instead of `libolm`.

Long story short, I'm wondering what the authors of Vodozemac think of [Rustler](https://github.com/rusterlium/rustler) to allow the BEAM ecosystem to use the library.

I could write a wrapper, but I'm just curious about your thoughts.

Cheers.

**Comment by poljar** [comment]
There are already some, albeit stale, bindings that use Rustler: https://gitlab.com/polyjuice/polyjuice_newt.

**Comment by shymega** [comment]
I didn't see that in my search. Is that documented on the Matrix.org docs?

Thank you!

**Comment by poljar** [comment]
> Is that documented on the Matrix.org docs?

Don't know, sorry.

**Comment by shymega** [comment]
One more thing - once I get the bindings updated, can we add the Rustler directory in the linked repo to the community bindings repo for Vodozemac?

**Comment by poljar** [comment]
The vodozemac-bindings repo has been quite dead as well, it's pretty hard to work on it as you'd need to update all the bindings at once.

As of now, I expect that smaller repos maintained by separate communities are the way to go, this might change in the future but it's my current view. For example, I also pulled out the [Python bindings](https://github.com/matrix-nio/vodozemac-python) and another community seems to have taken interest in the [c++ bindings](https://github.com/matrix-org/vodozemac-bindings/pull/8).
