### ISSUE TITLE
Replace `#[zeroize(drop)]` with `#[derive(ZeroizeOnDrop)]` when moving to `zeroize` 1.5.x

### ISSUE THREAD

**Issue by dkasak** [matrix-org/vodozemac#57]
In `zeroize` 1.5.x, the `#[zeroize(drop)]` attribute [was deprecated](https://docs.rs/zeroize/latest/zeroize/index.html#custom-derive-support) and replaced with `ZeroizeOnDrop`. We can't switch to newer `zeroize` versions due to dalek, but once we do, we should replace all uses of `#[zeroize(drop)]`.

**Comment by poljar** [comment]
This was fixed by: https://github.com/matrix-org/vodozemac/pull/159.
