### ISSUE TITLE
Update ed25519-dalek to allow rust-analyzer to work properly

### ISSUE THREAD

**Issue by ShadowJonathan** [matrix-org/vodozemac#61]
From #3, this is currently blocked as-is.

I'm converting that PR into an issue to track this problem, as [`ed25519-dalek`](https://github.com/dalek-cryptography/ed25519-dalek) has gone two years without a release, with some improvements on `master` branch that should be in a normal release.

Original issue, which is now closed as fixed, but not in a release yet: https://github.com/dalek-cryptography/ed25519-dalek/issues/173

Issue on their repo calling for a new release: https://github.com/dalek-cryptography/ed25519-dalek/issues/192

---

Alternatively, the following could be added to `.vscode/settings.json` to fix this for everyone using vscode;
```json5
  "rust-analyzer.cargo.unsetTest": [
    "core",
    "ed25519-dalek"
  ],
```

**Comment by poljar** [comment]
This is now presumably fixed since we do depend on a new release of ed25519-dalek as of: 11e81cda6473392aba1e4435c7f9b814cc31bdcc.
